config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :user, controllers: {  
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  namespace :admin do
    resources :jobs do
    member do
    post :publish
    post :hide
    end
    resources :resumes
    end
    
    resources :locations do
      member do
        post :publish
        post :hide
        post :up
        post :down
      end
    end

    resources :categories do
      member do
        post :publish
        post :hide
        post :up
        post :down
      end
    end
  end

  resources :jobs do
    resources :resumes
      member do
        post :add
        post :remove
      end
      collection do
        get :search
      end
  end
  
  namespace :account do
    resources :collections
    resources :resumes
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id         :integer          not null, primary key
#  name       :string
#  sort       :integer
#  is_hidden  :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Location < ApplicationRecord
    validates :name, presence: { message: "請輸入工作地點" }
    has_many :jobs
    scope :isshow, -> { where(is_hidden: false) }
    scope :orderbysort, -> { order("sort ASC") }
    scope :descbysort, -> { order("sort DESC") }
    def publish!
        self.is_hidden = false
        self.save
    end
    def hide!
        self.is_hidden = true
        self.save
    end
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < ApplicationController
    before_action :authenticate_user!
    before_action :require_is_dreamjob_admin
    before_action :find_by_locations_id, except: [:index ,:new, :create]
    layout "admin"
    def index
        @locations = Location.all.orderbysort
    end
    def new
        @location = Location.new
    end
    def create
        @location = Location.new(location_params)
        @location.sort = Location.descbysort.count == 0 ? 1 : Location.descbysort.first.sort + 1
        if @location.save
            redirect_to admin_locations_path,notice: "新增#{@location.name}成功"
        else
            render :new
        end
    end
    def edit        
    end
    def update
        if @location.update(location_params)
            redirect_to admin_locations_path,notice: "修改#{@location.name}成功"
        else
            render :edit
        end
    end
    def publish
        if @location.is_hidden?          
            @location.publish!
            redirect_back fallback_location: root_path, notice: "發布 #{@location.name}成功"
        else            
            redirect_back fallback_location: root_path,alert: "#{@location.name} 已經隱藏!"
        end                   
    end

    def hide
        if @location.is_hidden?          
            redirect_back fallback_location: root_path,alert: "#{@location.name} 已經發布!"
        else            
            @location.hide!
            redirect_back fallback_location: root_path, notice: "隱藏 #{@location.name}成功" 
        end                
    end
    def up
    @locationoriginal = Location.find_by(sort: @location.sort - 1)
    @location.sort -= 1
    
    if @location.sort > 0
      @location.save
    end
    #將要被排序的位置調換
    if @locationoriginal.present?
      @locationoriginal.sort += 1
      @locationoriginal.save
    end
        redirect_back fallback_location: root_path
    end
    def down    
        @locationoriginal = Location.find_by(:sort => @location.sort + 1)
        @location.sort += 1
        @location.save
            #將要被排序的位置調換
        if @locationoriginal.present?
            @locationoriginal.sort -= 1
            @locationoriginal.save
        end
        redirect_back fallback_location: root_path
    end
    private
    def location_params
        params.require(:location).permit(:name,:is_hidden)
    end
    def find_by_locations_id
        @location = Location.find(params[:id])
    end
end

app/helpers/admin/locations_helper.rb
module Admin::LocationsHelper
end

app/views/admin/locations/_form.html.erb
<div class="col-md-10 col-md-offset-1">
  <hr />
  <%= simple_form_for [:admin,@location] do |f| %>
    <div>
      <%= f.input :name, :label => false, placeholder: '請輸入工作地點' %>
      <hr />
      <span><%= f.input :is_hidden, label: '隱藏工作地點' %></span>
    </div>
    <div class="form-actions">
      <%= f.submit "送出", disable_with: "Submiting...", class: "button"%>
      <br/>      
      <%= link_to "返回工作地點", admin_locations_path %>
    </div>
  <% end %>
</div>

app/views/admin/locations/edit.html.erb
<div class="col-md-6 col-md-offset-3 admin-form">
  <div class="col-md-12 admin-form-content">
    <h2><span class="fa fa-location-arrow"> </span> 編輯工作地點</h2>
    <%= render('form') %>
  </div>
</div>

app/views/admin/locations/index.html.erb
<div class="col-md-8 col-md-offset-2 admin-box">
  <div class="row">
    <div class="col-md-12">
      <table class="table table-hover">
        <thead>
          <tr>
            <td colspan="6" class="title-box">
              <div class="title"><h2><span class="fa fa-location-arrow"></span> 工作地點</h2></div>
              <div class="button"><%= link_to("新增工作地點", new_admin_location_path, class: "btn btn-primary pull-right") %></div>
            </td>
          </tr>
        </thead>
        <tbody>
          <% i = 1 %>
          <% @locations.each do |location| %>
          <% if i%2 == 1%>
          <tr>
          <% end %>
            <td class="name-box"><%= location.sort %> <%= location.name %></td>
            <td class="action-box">
              <!--上移動/下移動/圖示 -->
              <div>
              <%= link_to(up_admin_location_path(location), :method => :post, class: "btn btn-md btn-default sort-btn") do %>
                <span class="fa fa-angle-up"></span>
              <% end %>
              <%= link_to(down_admin_location_path(location), :method => :post, class: "btn btn-md btn-default sort-btn") do %>
                <span class="fa fa-angle-down"></span>
              <% end %>
              <%= link_to(edit_admin_location_path(location), class: "btn btn-md btn-default") do %>
                <span class="fa fa-pencil"></span>
              <% end %>
              <!-- 工作地點隱藏 -->
              <% if location.is_hidden? %>
                <%= link_to(publish_admin_location_path(location), :method => :post, class: "btn btn-md btn-default show-btn") do %>
                  <span class="fa fa-eye-slash"></span>
                <% end %>
              <!-- 工作地點公開 -->
              <% else %>
                <%= link_to(hide_admin_location_path(location), :method => :post, class: "btn btn-md btn-default") do %>                  
                  <span class="fa fa-eye"></span>
                <% end %>
              <% end %>
              </div>
            </td>
          <% if i%2 == 0%>
          </tr>
          <% end %>
          <% i += 1 %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/locations/new.html.erb
<div class="col-md-6 col-md-offset-3 admin-form">
  <div class="col-md-12 admin-form-content">
    <h2><span class="fa fa-location-arrow"> </span> 新增工作地點</h2>
    <%= render('form') %>
  </div>
</div>