config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :user, controllers: {  
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  namespace :admin do
    resources :jobs do
    member do
    post :publish
    post :hide
    end
    resources :resumes
    end
    
    resources :locations do
      member do
        post :publish
        post :hide
        post :up
        post :down
      end
    end

    resources :categories do
      member do
        post :publish
        post :hide
        post :up
        post :down
      end
    end
  end

  resources :jobs do
    resources :resumes
      member do
        post :add
        post :remove
      end
      collection do
        get :search
      end
  end
  
  namespace :account do
    resources :collections
    resources :resumes
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id               :integer          not null, primary key
#  title            :string
#  description      :text
#  wage_upper_bound :integer
#  wage_lower_bound :integer
#  contact_email    :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  is_hidden        :boolean          default(FALSE)
#  user_id          :integer
#  categorie_id     :integer
#  location_id      :integer
#  company          :string
#

class Job < ApplicationRecord
    validates :title, :description,:contact_email ,presence: {message: "必填項目!"}
    validates :wage_upper_bound,numericality: { greater_than: 0, message: "請輸入金額而且大於0!" }
    validates :wage_lower_bound, numericality: { greater_than: 0, message: "請輸入金額而且大於0!"  }
    validates :company, presence: { message: "請填寫公司名稱" }
    validates :category, presence: { message: "請選擇職位類型" }
    validates :location, presence: { message: "請選擇公司地點" }
    validates_format_of :contact_email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i , message: "請輸入正確的信箱格式"

    scope :desc_by_created, ->{ order("created_at DESC") }
    scope :desc_by_wage_lower_bound, ->{ order("wage_lower_bound DESC") }
    scope :desc_by_wage_upper_bound, ->{ order("wage_upper_bound DESC") }
    scope :isshow, ->{ where(is_hidden: false) }
    scope :lowerbound5, -> { where('wage_lower_bound <= 5 or wage_upper_bound <= 5') }
    scope :lowerbound10, -> { where('wage_lower_bound between 5 and 10 or wage_upper_bound between 5 and 10') }
    scope :lowerbound15, -> { where('wage_lower_bound between 10 and 15 or wage_upper_bound between 10 and 15') }
    scope :lowerbound25, -> { where('wage_lower_bound between 15 and 25 or wage_upper_bound between 15 and 25') }
    scope :lowerbound30, -> { where('wage_lower_bound >= 25 or wage_upper_bound >= 25') }
    #隨機選擇5件
    scope :random5, -> { where(is_hidden: false).limit(5).order("RANDOM()") }
    
    belongs_to :user
    belongs_to :location
    belongs_to :category
    has_many :resumes, dependent: :destroy
    has_many :collections, dependent: :destroy
    has_many :members, through: :collections, source: :user
    
    def publish!
        self.is_hidden = false
        self.save
    end
    def hide!
        self.is_hidden = true
        self.save
    end
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_jobs_id_and_check_permission, except: [:index,:new,:create]
    before_action :require_is_admin
    layout "admin"

    def index        
        @locations = Location.isshow.orderbysort
        @categorys = Category.isshow.orderbysort        
        @jobs = helpers.searchs_jobs(params)             
    end
    def show        
    end
    def new
        @job = Job.new    
    end
    def create
        @job = Job.new(job_params)
        @job.user = current_user
        if @job.save
            redirect_to admin_jobs_path,notice: "新增#{@job.title}成功!"
        else
            render :new
        end
    end
    def edit
        @categorys = Category.isshow.orderbysort
        @locations = Location.isshow.orderbysort
    end
    def update
        if @job.update(job_params)
            redirect_to admin_jobs_path,notice: "修改#{@job.title}成功!"
        else
            render :edit
        end
    end
    def destroy
        @job.destroy
        redirect_to admin_jobs_path, alert: "刪除#{@Job.title}成功！"        
    end
    def publish
        if @job.is_hidden?          
            @job.publish!            
            redirect_back fallback_location: root_path, notice: "發布 #{@job.title}成功"
        else            
            redirect_back fallback_location: root_path,alert: "已經發布!"            
        end        
    end
    def hide        
        if @job.is_hidden?            
            redirect_back fallback_location: root_path,alert: "已經隱藏!" 
        else            
            @job.hide!            
            redirect_back fallback_location: root_path, notice: "隱藏 #{@job.title}成功"
        end
    end
    private
    def find_jobs_id_and_check_permission
        @job = Job.find(params[:id])

        if @job.user != current_user
            redirect_to root_path, alert: "您沒有權限進行此操作。"
        end
    end
    def job_params
        params.require(:job).permit(:title, :description, :company, :category_id, :location_id,
        :wage_upper_bound, :wage_lower_bound,:contact_email, :is_hidden)
    end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    before_action :find_jobs_id, only: [:edit, :update, :destroy, :show]
    before_action :authenticate_user!, except: [:index, :search]
    before_action :validates_search_key, only: [:search]
    def index
        @locations = Location.isshow.orderbysort
        @categorys = Category.isshow.orderbysort
        @recommand = Job.random5
        #判斷塞選
        #公司地點
        if params[:location].present?
            @location = params[:location]
            @location_id = Location.find_by(name: @location)
            if @location == "所有城市"
                @jobs = Job.isshow.desc_by_created.page(params[:page]).per(8)
            else
                @jobs = Job.where(location_id: @location_id).isshow.desc_by_created.page(params[:page]).per(8)            
            end
        #公司地點 end
        #職業類型
        elsif params[:category].present?
            @category = params[:category]
            @category_id = Category.find_by(name: @category)
            if @catrgory == "所有類型"
                @jobs = Job.isshow.desc_by_created.page(params[:page]).per(8)
            else
                @jobs = Job.where(category: @category_id ).isshow.desc_by_created.page(params[:page]).per(8)
            end
        #職業類型end
        elsif params[:bound].present?
            @bound = params[:bound]
            if @bound == '5k以下'
                @jobs = Job.isshow.lowerbound5.desc_by_created.page(params[:page]).per(8)
            elsif @bound == '5~10k'
                @jobs = Job.isshow.lowerbound10.desc_by_created.page(params[:page]).per(8)
            elsif @bound == '10~15k'
                @jobs = Job.isshow.lowerbound15.desc_by_created.page(params[:page]).per(8)
            elsif @bound == '15~25k'
                @jobs = Job.isshow.lowerbound25.desc_by_created.page(params[:page]).per(8)
            else
                @jobs = Job.isshow.lowerbound30.desc_by_created.page(params[:page]).per(8)
            end
        #預設全搜 但只搜尋自己所創建的工作
        else
            @jobs = Job.isshow.desc_by_created.page(params[:page]).per(8)
        end 
    end
    def show       
        not_allow_view_hidden_jobs(@job)
        @category = @job.category
        #扣掉當前職位以及隨機挑選5職位
        @randomjobs = Job.where(category: @job.category).where.not(id: @job.id).isshow.random5
        @resumes = Resume.where(job: @job,user: current_user)
    end
    def add
        @job = Job.find(params[:id])

        unless current_user.is_colectedmember_of?(@job)
            current_user.add_collection!(@job)    
        end
        
        render "collection"        
        
        #redirect_back fallback_location: root_path, notice: "#{@job.title}儲存喜愛工作成功!"         
    end
    
    def remove
        @job = Job.find(params[:id])

        if current_user.is_colectedmember_of?(@job)
        current_user.remove_collection!(@job)
        end
        
        render "collection"
        
        #redirect_back fallback_location: root_path, warning: "#{@job.title}從喜愛工作移除成功!"
    end

    def search        
        #隨機推薦5個職位
        @recommand = Job.random5
        if @query_string.present?        
            #使用like 搜尋職位
            search_result = Job.ransack(@search_criteria).result(distinct: true)
            @jobs = search_result.isshow.page(params[:page]).per(8)            
        else
            @jobs = Job.isshow.desc_by_created.page(params[:page]).per(8)            
        end
    end   
    private
    def validates_search_key
        # 去除特殊字符 #
        @query_string = params[:keyword].gsub(/\\|\'|\/|\?/, "") if params[:keyword].present?
        @search_criteria = search_criteria(@query_string)
    end
    
    def search_criteria(query_string)
        #塞選多欄位
        { title_or_company_or_location_name_cont: query_string }
    end

    def find_jobs_id
        @job = Job.find(params[:id])
    end
    
    def jobs_params
        params.require(:job).permit(:title, :description, :wage_upper_bound,:wage_lower_bound,:contact_email)
    end
    
    def not_allow_view_hidden_jobs(job)
        if job.is_hidden?
            redirect_to jobs_path, warning: "此工作已被隱藏!您無法查看!"
        end
    end
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper

end

app/helpers/jobs_helper.rb
module JobsHelper
    #工作隱藏顯示圖示
    def render_job_status(job)    
        if job.is_hidden?
            "fa fa-lock"
        #content_tag(:span, "", class: "fa fa-lock")
        else
        #content_tag(:span, "" ,class: "fa fa-globe")
        "fa fa-globe"
        end                    
    end
    #工作內容
    def render_jobs_description(job)
        simple_format(job.description)
    end
    #薪水區間
    def render_job_bound(job)
        "#{job.wage_lower_bound} k ~ #{job.wage_upper_bound} k"
    end
    # 是否投遞過履歷icon
    def render_job_resumes(job)
        if job.resumes.count > 0
        "fa fa-envelope-open-o"
        else
        "fa fa-envelope-o"
        end
    end
    #收藏icon
    def render_job_collections(job)
        if job.collections.count > 0
        "fa fa-heart"
        else
        "fa fa-heart-o"
        end
    end
    #是否隱藏該職缺
    def render_job_hidden(job)
        if job.is_hidden
        "hidden-box"
        end
    end
    def date_add8hour(job)
        result = job.created_at + 8.hours
        result.strftime("%Y年%m月%d日 %H:%M")
    end
end

app/views/admin/jobs/_form.html.erb
<div class="col-md-10 col-md-offset-1 job-form-content">
  <hr style="size:2px" />
  <%= simple_form_for [:admin,@job] do |f| %>
    <div class="form-group">
      <%= f.input :title, :label => false, placeholder: '請輸入職位名稱' %>
      <%= f.input :description, :label => false, placeholder: '請輸入職位描述', input_html: { class: 'job-content-info' } %>
      <%= f.input :company, :label => false, placeholder: '請輸入公司名稱' %>
      <hr />
      <%= f.input :category_id, :label => "職位類型", :collection => Category.isshow.orderbysort, :checked => @job.category, input_html: { class: 'category' } %>
      <%= f.input :location_id, :label => "工作地點", :collection => Location.isshow.orderbysort, :checked => @job.location, input_html: { class: 'location' } %>
      <%= f.input :form_bound, :label => '薪資' do %>
         <%= f.input_field :wage_lower_bound, :as => :string, class: "bound" %> <span class="bound-form">k ~</span>
         <%= f.input_field :wage_upper_bound, :as => :string, class: "bound" %> <span class="bound-form">k</span>
      <% end %>
      <%= f.input :contact_email, label: '聯絡方式', placeholder: 'user@example.com' %>
      <hr />
      <span class="hidden-box"><%= f.input :is_hidden, label: '隱藏職位' %></span>
    </div>
    <div class="form-actions">
      <%= f.submit "送出", disable_with: "Submiting...", class: "button"%>
    </div>
  <% end %>
</div>

app/views/admin/jobs/edit.html.erb
<div class="col-md-6 col-md-offset-3 job-form">
    <div class="col-md-12 job-form-content">
      <h2><span class="	fa fa-address-card-o"></span> 修改職位</h2>
      <%= render('form') %>
    </div>
</div>

app/views/admin/jobs/index.html.erb
<div class="col-md-12">
  <div class="row">
    <div class="col-md-12 btn-group admin-select-job-box">
      <!-- 工作地點下拉選單 ===-->
      <div class="dropdown btn-group clearfix">
        <% if @location.present? %>
          <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            <%= @location %> <span class="caret"></span>
          </button>
        <% else %>
          <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            工作地點 <span class="caret"></span>
          </button>
        <% end %>
        <ul class="dropdown-menu" selection aria-labelledby="dropdownMenuDivider">
          <% @locations.each do |location| %>
          <li>
            <%= link_to(location.name, admin_jobs_path(location: location.name)) %>
          </li>
          <% end %>
          <li>
            <%= link_to("所有城市", admin_jobs_path(:location => "所有城市") ) %>
          </li>
        </ul>
      </div>

      <!-- 職位類型下拉選單 -->
      <div class="dropdown btn-group clearfix">
        <% if @category.present? %>
        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          <%= @category %> <span class="caret"></span>
        </button>
        <% else %>
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          職位類型 <span class="caret"></span>
        </button>
        <% end %>
        <ul class="dropdown-menu" selection aria-labelledby="dropdownMenuDivider">
          <% @categorys.each do |category| %>
          <li>
            <%= link_to(category.name, admin_jobs_path(:category => category.name)) %>
          </li>
          <% end %>
          <li>
            <%= link_to("所有類型", admin_jobs_path(category: "所有類型") ) %>
          </li>
        </ul>
      </div>

      <!-- 月薪下拉選單 -->
      <div class="dropdown btn-group clearfix">
        <% if @bound.present? %>
        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          <%= @bound %> <span class="caret"></span>
        </button>
        <% else %>
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          月薪 <span class="caret"></span>
        </button>
        <% end %>
        <ul class="dropdown-menu" selection aria-labelledby="dropdownMenuDivider">
          <li>
            <%= link_to("5k以下", admin_jobs_path(bound: "5k以下")) %>
          </li>
          <li>
            <%= link_to("5~10k", admin_jobs_path(bound: "5~10k")) %>
          </li>
          <li>
            <%= link_to("10~15k", admin_jobs_path(bound: "10~15k")) %>
          </li>
          <li>
            <%= link_to("15~25k", admin_jobs_path(bound: "15~25k")) %>
          </li>
          <li>
            <%= link_to("25k以上", admin_jobs_path(bound: "25k以上")) %>
          </li>
        </ul>
      </div>

      <!--=== 新增職位 ===-->
      <div class="job">
        <%= link_to("新增職位", new_admin_job_path, class: "btn btn-primary pull-right action-btn") %>
      </div>
    </div>
  </div>
  <div class="admin-job-box">
<% if @jobs.length > 0 %>
  <table class="table">
    <thead>
      <tr>
        <td>招聘職位</td>
        <td>職位類型</td>
        <td>公司名稱</td>
        <td>工作地點</td>
        <td>新增範圍</td>
        <td>簡歷收藏/收藏</td>
        <td>發布時間</td>
        <td class="count">已發布職位: <span><%= @jobs.count %></span></td>
      </tr>
    </thead>
    <tbody>
      <% @jobs.each do |job| %>
      <!-- 顯示工作是否隱藏 -->
      <tr class="job-list <%= render_job_hidden(job) %>">
        <!-- 職位 -->
        <td class="title"><span class="<%= render_job_status(job) %>"></span> <%= link_to(job.title, job_path(job)) %></td>
        <!-- 職位類別 -->
        <td><span class="<%= job.category.icon %>"> <%= job.category.name %></td>
        <!-- 公司名稱 -->
        <td><%= job.company %></td>
        <!-- 公司地點 -->
        <td><span class="fa fa-map-marker"></span> <%= job.location.name %></td>
        <!-- 薪水 -->
        <td class="bound"><%= render_job_bound(job) %></td>
        <!-- 履歷 -->
        <td>
          <%= link_to admin_job_resumes_path(job) do %><span class="<%= render_job_resumes(job) %>"></span> <%= job.resumes.count %><% end %> /
          <span class="<%= render_job_collections(job) %>"></span> <%= job.collections.count %>
        </td>
        <!-- 發佈時間 -->
        <td><%=  date_add8hour(job) %></td>
        <td>
          <!-- 修改/隱藏/icon -->
          <div class="action-box">
          <%= link_to(edit_admin_job_path(job), class: "btn btn-md btn-default") do %>
            <span class="fa fa-pencil"></span>
          <% end %>

          <% if job.is_hidden? %>
            <%= link_to(publish_admin_job_path(job), :method => :post, class: "btn btn-md btn-default show-btn") do %>
              <span class="fa fa-eye-slash"></span>
            <% end %>
          <% else %>
            <%= link_to(hide_admin_job_path(job), :method => :post, data: { confirm: "確認隱藏#{job.title}職位?" }, class: "btn btn-md btn-default") do %>              
              <span class="fa fa-eye"></span>
            <% end %>
          <% end %>
          </div>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h3 class="no-data">目前尚未發布職缺，趕快去新增吧。</h3>
<% end %>
</div>
  <div class="col-md-12 job-bottom">
    <div class="text-center">
        <%= paginate @jobs %>
    </div>
  </div>
</div>

app/views/admin/jobs/new.html.erb
<div class="col-md-6 col-md-offset-3 job-form">
    <div class="col-md-12 job-form-content">
      <h2><span class="	fa fa-address-card-o"></span> 新增職位</h2>
      <%= render('form') %>
    </div>
</div>

app/views/admin/jobs/show.html.erb
<div class="col-md-10 col-center">
<div class="panel panel-default">
 <div class="panel-heading">
    <h3 class="panel-title"><%= @job.title %> </h3>
  </div>
<div class="panel-body">   
<p><%= render_jobs_description(@job) %></p>
<table class="table">
<thead>
<tr>
<div class="text-center">
  
</div>
</tr>
</thead>
<tbody>

</tbody>
</table>
  </div>
<%= link_to "回首頁", root_path,  class: "btn btn-primary pull-right" %>
</div>
</div>
 
  