config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :user, controllers: {  
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  namespace :admin do
    resources :jobs do
    member do
    post :publish
    post :hide
    end
    resources :resumes
    end
    
    resources :locations do
      member do
        post :publish
        post :hide
        post :up
        post :down
      end
    end

    resources :categories do
      member do
        post :publish
        post :hide
        post :up
        post :down
      end
    end
  end

  resources :jobs do
    resources :resumes
      member do
        post :add
        post :remove
      end
      collection do
        get :search
      end
  end
  
  namespace :account do
    resources :collections
    resources :resumes
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  icon       :string
#  sort       :integer
#  is_hidden  :boolean          default(FALSE)
#  is_lock    :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ApplicationRecord
    validates :name, presence: {message: "請輸入種類名稱!"}
    validates :icon, presence: {message: "請輸入icon代碼!"}
    has_many :jobs
    scope :isshow, -> { where(is_hidden: false) }
    scope :orderbysort, -> { order("sort ASC") }
    scope :descbysort, -> { order("sort DESC") }
    def publish!
        self.is_hidden = false
        self.save
    end
    def hide!
        self.is_hidden = true
        self.save
    end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_is_dreamjob_admin
  before_action :find_category_id, except: [:index, :new , :create]
  layout "admin"
    def index
        @categorys = Category.all.orderbysort
    end

    def new
        @category = Category.new
    end
    def create
        @category = Category.new(category_params)
        @category.sort = Category.descbysort.count == 0 ? 1 : Category.descbysort.first.sort + 1        
        if @category.save      
            redirect_to admin_categories_path, notice: "#{@category.name}職位新增成功"
        else
            render :new
        end
    end
    def edit      
    end
    def update
        if  @category.update(category_params)
            redirect_to admin_categories_path, notice: "#{@category.name}職位修改成功"
        else
            render :edit
        end    
    end

    def publish
        if @category.is_hidden?          
            @category.publish!      
            redirect_back fallback_location: root_path, notice: "發布 #{@category.name}成功"
        else                        
            redirect_back fallback_location: root_path, alert: "#{@category.name} 已經發布!"
        end 
    end
    def hide
        if @category.is_hidden?          
            redirect_back fallback_location: root_path, alert: "#{@category.name} 已經隱藏!"
        else                                    
            @category.hide!      
            redirect_back fallback_location: root_path, notice: "隱藏 #{@category.name}成功"
        end       
    end

    #往上排序 此工作排序 -1
    def up      
      @categoryoriginal = Category.find_by(sort: @category.sort - 1)      
      @category.sort -= 1

      #排序數字 大於0才存檔
      if @category.sort > 0
        @category.save
      end
      
      #將要被排序的位置調換
      if @categoryoriginal.present?
        @categoryoriginal.sort += 1
        @categoryoriginal.save
      end

      redirect_back fallback_location: root_path
    end
    
    #+1做排序動作
    def down      
      @categoryoriginal = Category.find_by(:sort => @category.sort + 1)
      @category.sort += 1
      @category.save

      #將要被排序的位置調換
      if @categoryoriginal.present?
        @categoryoriginal.sort -= 1
        @categoryoriginal.save
      end

      redirect_back fallback_location: root_path
    end

    private

    def find_category_id
        @category = Category.find(params[:id])
    end
    def category_params
        params.require(:category).permit(:name, :icon, :is_hidden)
    end
end

app/helpers/admin/category_helper.rb
module Admin::CategoryHelper
end

app/views/admin/categories/_form.html.erb
<div class="col-md-10 col-md-offset-1">
  <hr />
  <%= simple_form_for [:admin , @category] do |f| %>
    <div>
      <%= f.input :name, :label => false, placeholder: '請輸入職位類型' %>
      <%= f.input :icon, :label => false, placeholder: '請輸入ICON代碼（例如：fa-home）' %>
      <hr />
      <span><%= f.input :is_hidden, label: '隱藏職位' %></span>
    </div>
    <div class="form-actions">
      <%= f.submit "送出", disable_with: "Submiting...", class: "button"%>
      <br/>      
      <%= link_to "返回職位類型", admin_categories_path %>
    </div>
  <% end %>
</div>

app/views/admin/categories/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="col-md-12  admin-form-content" >
    <h2><span class="fa fa-cogs"> </span> 編輯職位類型</h2>    
    <%= render 'form' %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="col-md-8 col-md-offset-2 admin-box">
  <div class="row">
    <div class="col-md-12">
      <table class="table table-hover">
        <thead>
          <tr>
            <td colspan="6" class="title-box">
              <div class="title"><h2><span class="fa fa-cogs"></span> 職位類型</h2></div>
              <div class="button"><%= link_to("新增職位類型", new_admin_category_path, class: "btn btn-primary pull-right") %></div>
            </td>
          </tr>
        </thead>
        <tbody>
          <% i = 1 %>
          <% @categorys.each do |category| %>
          <% if i%2 == 1%>
          <tr>
          <% end %>
            <td class="name-box"><%= category.sort %> <span class="<%= category.icon %>"></span> <%= category.name %></td>
            <td class="action-box">
              <!-- 修上移/下移/圖示 -->
              <div>
              <%= link_to(up_admin_category_path(category), :method => :post, class: "btn btn-md btn-default sort-btn") do %>
                <span class="fa fa-angle-up"></span>
              <% end %>
              <%= link_to(down_admin_category_path(category), :method => :post, class: "btn btn-md btn-default sort-btn") do %>
                <span class="fa fa-angle-down"></span>
              <% end %>
              <!-- 修上移/下移/圖示 end -->              
              <!--=== 鎖定 不可編輯===-->
              <% if category.is_lock? %>
              <span class="fa fa-pencil btn btn-md btn-default lock-btn" disabled="disabled"></span>
              <span class="fa fa-eye-slash btn btn-md btn-default lock-btn" disabled="disabled"></span>
              <!-- 類型無鎖定 可編輯-->
              <% else %>
                <%= link_to(edit_admin_category_path(category), class: "btn btn-md btn-default") do %>
                  <span class="fa fa-pencil" disabled="disabled"></span>
                <% end %>
              <% end %>
              <!--=== 類型隱藏 ===-->
              <% if category.is_hidden? %>
                <%= link_to(publish_admin_category_path(category), :method => :post, class: "btn btn-md btn-default show-btn") do %>
                <span class="fa fa-eye-slash"></span>
                <% end %>
              <!--=== 類型公開 ===-->
              <% else %>
                <%= link_to(hide_admin_category_path(category), :method => :post, class: "btn btn-md btn-default") do %>                  
                  <span class="fa fa-eye"></span>
                <% end %>
              <% end %>              
              </div>
            </td>
            <% if i%2 == 0%>
              </tr>
            <% end %>
          <% i += 1 %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/categories/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="col-md-12 admin-form-content">
    <h2><span class="fa fa-cogs"> </span> 新增職位類型</h2>    
    <%= render 'form' %>
  </div>
</div>