config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :user, controllers: {  
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  namespace :admin do
    resources :jobs do
    member do
    post :publish
    post :hide
    end
    resources :resumes
    end
    
    resources :locations do
      member do
        post :publish
        post :hide
        post :up
        post :down
      end
    end

    resources :categories do
      member do
        post :publish
        post :hide
        post :up
        post :down
      end
    end
  end

  resources :jobs do
    resources :resumes
      member do
        post :add
        post :remove
      end
      collection do
        get :search
      end
  end
  
  namespace :account do
    resources :collections
    resources :resumes
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
    <% user_facing_flashes.each do |key,value| %>
    <div class="alert flashbar alert-dismissable alert-<%= flash_class(key) %> <%= ' session-login-navbar' if controller_name == "sessions" %>">
    <button class="close" data-dismiss="alert">X</button>
    <%= value %>
    </div>
    <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
      <div class="row jobinfo">
        <!-- 工作機會 -->
        <div class="col-md-2">
          <h4>工作機會</h4>
          <ul class="list">
            <li><a href="#">求職專區 </a></li>
            <li><a href="#">海外工作 </a> </li>
            <li><a href="#">外包專區 </a> </li>
          </ul>
        </div>
        <!-- 工作機會 end -->
        <!-- 企業資源 -->
        <div class="col-md-2">
          <h4>企業資源</h4>
          <ul class="list">
            <li><a href="#">企業培訓 </a></li>
            <li><a href="#">聯合招募 </a> </li>
            <li><a href="#">企業實習 </a> </li>
          </ul>
        </div>
        <!-- 企業資源 end -->
        <!-- 關於我們 -->
        <div class="col-md-2">
          <h4>關於我們</h4>
          <ul class="list">
            <li><a href="#">公司介紹</a></li>
            <li><a href="#">問題反應</a> </li>
            <li><a href="http://gregyang.logdown.com">聯繫方式</a> </li>
          </ul>
        </div>
        <!-- 關於我們 end -->
        <div class="col-md-6">
          <div class="linktoimg">
            <a href="#"> <%= image_tag "company/facebooklink.png" %> </a>
            <a href="#"> <%= image_tag "company/Linked-Inlink.png" %></a>
            <a href="#"> <%= image_tag "company/twitterlink.png" %></a>
          </div>
          <div class="linktoauthor">
          <a href="http://gregyang.logdown.com">
            <%= image_tag "company/logdownlogo.png" %>
            Welcome to My Blog
          </a>
          </div>
        </div>
      </div>
      <hr>
        <p class="text-center">Copyright ©2018 | Dream Job |
            Design by
            <a href="http://gregyang.logdown.com" target=_new>Greg</a>
        </p>
      </div>
    </div>
  </div>
 </footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top default-menu" role="navigation">
    <div class="container-fluid container">
        <div class="navbar-header">
        <a class="navbar-brand default_logo" href="/">
        <%= image_tag 'logo.png', class: "logo_img", alt: "logo"%>                 
            Dream Job</i></a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-left btn-welcome-nav">
            <li> <a href="/"><i class="fa fa-home"> 首頁 </i></a></li>
            <li> <a href="/jobs"><i class="fa fa-briefcase"> 工作 </i></a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right btn-welcome-nav">
                <% if !current_user %>                        
                <li><%= link_to "註冊", new_user_registration_path %></li>
                <li><%= link_to "登入", new_user_session_path %></li>                                     
                <% else %>
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <%= current_user.nickname %> ， 您好!
                    <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">                                    
                        <% if current_user.admin?  %>
                        <li><%= link_to "企業專區", admin_jobs_path %> </li>
                        <li class="divider"> </li>
                        <% end %>            
                        <li> <%= link_to "我的收藏工作", account_collections_path %> </li> 
                        <li> <%= link_to "我的投遞歷史", account_resumes_path %> </li> 
                        <li class="divider"> </li>
                        <li><%= link_to "登出", destroy_user_session_path,method: :delete %> </li>
                    </ul>
                    </li>
                <% end %>                    
            </ul>
            <!--=== 搜索欄 ===-->
            
            <%= form_tag search_jobs_path, method: :get, class: "navbar-form navbar-right search-form" do %>
            <div class="input-group search-box">         
                <input type="text" class="form-control" name="keyword" placeholder="搜尋職位、公司、地點。" value="<%= params[:keyword] %>">
            <div class="input-group-btn">           
                <%= button_tag(type: "submit", class: "btn btn-default") do %>
                    <i class="fa fa-search"></i>
                <% end %>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</nav>